config/routes.rb
RailsApp::Application.routes.draw do
  get  'uploads/shp' => 'uploads#form'
  post 'uploads/shp' => 'uploads#confirm'
  get "login"                                => 'accounts#index', as: :login_and_register_page
  get "confirm_email/:confirmation_token"    => 'accounts#confirm_email', as: :confirm_email
  get "reset_password/:reset_password_token" => 'accounts#reset_password_start', as: :reset_password_start

  post "login"           => 'accounts#login'
  get  "logout"          => 'accounts#logout'
  post "register"        => 'accounts#register'
  post 'forgot_password' => 'accounts#forgot_password'
  post 'reset_password/:reset_password_token' => 'accounts#reset_password_finish', as: :reset_password_finish

  namespace :dev do
    get 'es_agri'     => 'es#agri'
    get 'es_plants'   => 'es#plants'
    get 'es_precinct' => 'es#precinct'
    get 'es_precinct_fields' => 'es#precinct_fields'

    get "modules" => 'modules#index'
    get "templates" => 'templates#index'
    get "templates/field_card" => 'templates#field_card'
    get "js" => 'js#index'
  end

  namespace :api do
    post "logger/error"
    post "emails/invite_friends" => 'send_mails#invite_friends', as: :send_email_invite_friends
    get  "profiles/own" => 'profiles#show_own',         as: :profiles_own
    put  "profiles/own" => 'profiles#update_own',       as: :profiles_own
    post "profiles/own" => 'profiles#change_password',  as: :profiles_own
    get  "settings"     => 'settings#index',            as: :settings
    put  "settings"     => 'settings#update',           as: :settings
    scope ':season', :season => /\d{4}/ do
    end

    get   "farms"             => 'farms#index',        as: :farms_index
    get   "farms/:id"         => 'farms#show',         as: :farms_show
    get   "farms/:id/seasons" => 'farms#farm_seasons', as: :farm_seasons_show
    post  "farms"             => 'farms#create', as: :farms_create
    put   "farms/:id"         => 'farms#update', as: :farms_update

    post  "farm_in_seasons/active_deactive/:id" => 'farm_in_seasons#active_deactive', as: :active_deactive_farm_in_season

    get   "seasons"           => "seasons#index", as: :seasons_index
    get   "seasons/:id/farms" => "seasons#season_farms", as: :season_farms_show

    get    'fis/:fis_id/fields'     => 'fields#index',  as: :fields_index   # localhost:3000/api/fis/19/fields
    post   'fis/:fis_id/fields'     => 'fields#create', as: :fields_create  # localhost:3000/api/fis/19/fields
    put    'fis/:fis_id/fields/:id' => 'fields#update', as: :fields_update  # localhost:3000/api/fis/19/fields/10
    delete 'fis/:fis_id/fields/:id' => 'fields#delete', as: :fields_delete  # localhost:3000/api/fis/19/fields/10
    get 'dicts/get_precinct' => 'dicts#get_precinct', as: :get_precinct

    get 'dicts/search_plants'    => 'dicts#search_plants',    as: :search_plants
    get 'dicts/search_agri_pack' => 'dicts#search_agri_pack', as: :search_agri_pack
    get 'dicts/search_precinct'  => 'dicts#search_precinct',  as: :search_precinct
    get 'dicts/search_precinct_by_code' => 'dicts#search_precinct_by_code', as: :search_precinct_by_code

    post "files/upload_shape"  => 'files_upload#upload_shape', as: :upload_shape

    get 'parcels_by_geo'       => 'parcels#by_geo', as: :parcels
  end

  root :to => 'home#index'
  get  "help"          => 'home#help'
  get  "home/index"
  get  "home/wizard"
  post "home/wizard_completed"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authorize_by_token
  layout 'empty', :only => [:wizard]

  def index
    seasons, farms = Set.new, Set.new

    FarmInSeason.joins(:user_on_farms).where(user_on_farms: {user_id: @current_user.id}).map do |i|
      farms.add({name: i.farm.shortname, id: i.farm.id})
      seasons.add({name: i.season.name, id: i.season.id})
    end

    proffer current_user: @current_user, seasons: seasons, farms: farms, env: Rails.env
  end

  def wizard
    if FarmInSeason.joins(:user_on_farms).where(user_on_farms: {user_id: @current_user.id}).count > 0
      return redirect_to :controller => 'home', :action => 'index'
    end
    current_year = DateTime.now.year
    proffer token: session[:token], current_year: current_year, current_user: @current_user
  end

  def wizard_completed
    session[:token] = params[:token]
    first_year_of_season, farm_name, farm_shortname = params[:season], params[:name], params[:short_name]
    season = Season.where(first_year: first_year_of_season.to_i).first
    farm = Farm.create(name: farm_name, shortname: farm_shortname)

    fis = FarmInSeason.new.tap do |fis|
      fis.season_id = season.id
      fis.farm_id   = farm.id
      fis.active    = true

      fis.save
    end

    UserOnFarm.new.tap do |uof|
      uof.user = @current_user
      uof.farm_in_season = fis
      uof.role = FarmRoles::OWNER
    end.save

    UserSettingsUpdater.update(@current_user, 'fis_id' => fis.id)
    @current_user.save
    redirect_to :controller => 'home', :action => 'index'
  end

  def help
  end
end

app/views/home/index.html.haml
- @settings = user_settings(current_user)

- content_for :scripts do
  :coffeescript
    propagateErrors = "#{env}" is 'development'

    window.App.config =
      ErrorLogger:
        propagateErrors: propagateErrors
        url: "#{api_logger_error_url}"
        user: "#{current_user.email}"
        token: "#{current_user.auth_token}"

      HttpTransaction:
        token: "#{current_user.auth_token}"

      ModuleManager:
        modulesNamespace: window.App.Modules

      ModelProvider:
        modelsNamespace: window.App.Models
        collectionsNamespace: window.App.Collections

      CoreInitializer:
        modules: ['InviteFriends','Season', 'Pagination', 'Dashboard', 'Profile', 'Farm', 'FieldCard', 'ParcelsService', 'Geometry', 'SearchLocation', 'Map', 'WeatherService']

      PageSidebar:
        minimized: #{@settings['ui_sidebar_minimized'] || false}

      Map: {}

      ParcelsService: {}

      TemplateProvider:
        templatesNamespace: window.HandlebarsTemplates || window.tpl
        templatePrefix: if window.HandlebarsTemplates? then 'app/templates' else null

      SettingManager:
        data: #{@settings.to_json}

    window.App.urls =
      ModuleDownloaderUrl: 'none'
      InviteFriendsUrl: "#{api_send_email_invite_friends_url}"
      SeasonUrl: 'none'
      ProfileOwnUrl: "#{api_profiles_own_url}"
      FarmsUrl: "#{api_farms_index_url}"
      SeasonsUrl: "#{api_seasons_index_url}"
      SettingsUrl: "#{api_settings_url}"
      ParcelsUrl: "#{api_parcels_url}"
      FieldsUrl: "#{api_fields_index_url(fis_id: ':FIS_ID')}"
      DefaultAvatarImageUrl: "#{image_path('themes/avatars/avatar_default.jpg')}"
      SearchLocation:
        LocationByNameUrl: 'http://nominatim.openstreetmap.org/search'
        LocationByGeoUrl: 'http://nominatim.openstreetmap.org/reverse'
      SearchPrecinct:
        BaseUrl: "#{api_search_precinct_url}"
        ByCodeUrl: "#{api_search_precinct_by_code_url}"


    initializer = new window.App.Core.Initializer(window.App.config, window.App.urls)
    initializer.init()
    initializer.registerBaseModules()
    initializer.registerModules()
    initializer.startHistory()

app/views/home/wizard.html.haml
.setup-wizzard
  .page-content
    .row
      .col-xs-12
        .row-fluid
          .span12
            #baseConfigurationWizard
              #fuelux-wizard.row-fluid{"data-target" => "#step-container"}
                .center
                  %h2.bolder.green
                    %i.icon-gears
                    Konfiguracja konta
                %hr
                %ul.wizard-steps
                  %li.active{"data-target" => '#step1'}
                    %span.step 1
                    %span.title Wprowadzenie
                  %li{"data-target" => '#step2'}
                    %span.step 2
                    %span.title Ustawienie sezonu
                  %li{"data-target" => '#step3'}
                    %span.step 3
                    %span.title Wprowadzenie gospodarstwa
                  %li{"data-target" => '#step4'}
                    %span.step 4
                    %span.title Zakończenie
              #step-container.step-content.row-fluid.position-relative
                #step1.step-pane.active
                  %h2.header.green.top-m25.center Krok 1 - wprowadzenie
                  .clear-b.center
                    %h3.green
                      %i.icon-leaf
                      Witamy w
                      %span.bolder EFarm.pl
                    %p Aby rozpocząć pracę w sytemie, należy wprowadzić kilka podstawowych danych. Które pozwolą kontynuować pracę w systemie.
                    %h5 Powodzenia!
                #step2.step-pane
                  %h2.header.green.top-m25.center Krok 2 - Wybierz sezon
                  %ul.js-wizard-seasons.dotted-steps.clearfix

                  .setup-wizzard-info-box.blue.align-center
                    %h4.bolder
                      %i.icon-info-circle
                      Sezon ma na celu:
                    %p Zgrupować prace przeporowazanie w gospodarstwie.
                    %p Zaznaczyć początek oraz koniec zbiorów.
                    %p Na jego podstawie stworzysz raporty które pomogą określić zyski i straty związane z pracami w gospodarswie.

                #step3.step-pane
                  %h2.header.green.top-m25.center Krok 3 - Dane gospodarstwa
                  %h4.bolder.center.blue Podstawowe informacje
                  %form#wizardSetupFarm.form-horizontal{method: 'POST', action: home_wizard_completed_url(token: token)}
                    %input#season{name: "season", type: "hidden", value: "#{current_year}"}
                    .form-group
                      %label.control-label.col-xs-12.col-sm-4.no-padding-right.bolder.blue{for: "name"} Nazwa
                      .col-xs-12.col-sm-8
                        .clearfix
                          %input#name.col-xs-12.col-sm-6{name: "name", type: "text", value: ""}
                    .form-group
                      %label.control-label.col-xs-12.col-sm-4.no-padding-right.bolder.blue{for: "shortName"} Nazwa skrócona
                      .col-xs-12.col-sm-8
                        .clearfix
                          %input#shortName.col-xs-12.col-sm-6{name: "short_name", type: "text", value: ""}
                #step4.step-pane
                  %h2.header.green.top-m25.center Krok 4
                  .clear-b.center
                    %h4.bolder.blue Gratulacje!
                    %p Podstawowe dane zostały wypełnione, teraz możesz jeszcze polecić znajomym nasz serwis lub zapisać dane i kontynuować pracę.
                    %p
                      %button#wizardBtnInviteFriend.btn.btn-primary.btn-large
                        %i.icon-group
                        Poleć znajomym
              .footer.wizard-actions
                %button.btn.btn-small.btn-prev
                  %i.icon-arrow-left
                  Wstecz
                %button.btn.btn-success.btn-small.btn-next{"data-last" => "Zakończ"}
                  Dalej
                  %i.icon-arrow-right.icon-on-right

            - content_for :scripts do
              %script#seasonElem{type: 'text/x-handlebars-template'}
                {{#each seasons}}
                %li{class: "{{#if selected}}selected{{/if}}", "data-year" => "{{value}}", style: "min-width: 20%; max-width: 20%;"}
                  %span.step
                  %span.title {{name}}
                {{/each}}

              = javascript_include_tag 'page_home'
              :coffeescript
                window.App.config =
                  ErrorLogger:
                    propagateErrors: false
                    url: "#{api_logger_error_url}"
                    user: "#{current_user.email}"
                    token: "#{current_user.auth_token}"

                  HttpTransaction:
                    token: "#{current_user.auth_token}"

                  ModuleManager:
                    modulesNamespace: window.App.Modules

                  ModelProvider:
                    modelsNamespace: window.App.Models
                    collectionsNamespace: window.App.Collections

                  CoreInitializer:
                    modules: ['InviteFriends']

                  TemplateProvider:
                    templatesNamespace: window.HandlebarsTemplates || window.tpl
                    templatePrefix: if window.HandlebarsTemplates? then 'app/templates' else null

                window.App.urls =
                  InviteFriendsUrl: "#{api_send_email_invite_friends_url}"
                  ModuleDownloaderUrl: 'none'

                initializer = new window.App.Core.Initializer(window.App.config, window.App.urls)
                initializer.init()
                initializer.registerModules()
                new window.App.Controllers.ConfigurationWizard(#{current_year})