config/routes.rb
RailsApp::Application.routes.draw do
  get  'uploads/shp' => 'uploads#form'
  post 'uploads/shp' => 'uploads#confirm'
  get "login"                                => 'accounts#index', as: :login_and_register_page
  get "confirm_email/:confirmation_token"    => 'accounts#confirm_email', as: :confirm_email
  get "reset_password/:reset_password_token" => 'accounts#reset_password_start', as: :reset_password_start

  post "login"           => 'accounts#login'
  get  "logout"          => 'accounts#logout'
  post "register"        => 'accounts#register'
  post 'forgot_password' => 'accounts#forgot_password'
  post 'reset_password/:reset_password_token' => 'accounts#reset_password_finish', as: :reset_password_finish

  namespace :dev do
    get 'es_agri'     => 'es#agri'
    get 'es_plants'   => 'es#plants'
    get 'es_precinct' => 'es#precinct'
    get 'es_precinct_fields' => 'es#precinct_fields'

    get "modules" => 'modules#index'
    get "templates" => 'templates#index'
    get "templates/field_card" => 'templates#field_card'
    get "js" => 'js#index'
  end

  namespace :api do
    post "logger/error"
    post "emails/invite_friends" => 'send_mails#invite_friends', as: :send_email_invite_friends
    get  "profiles/own" => 'profiles#show_own',         as: :profiles_own
    put  "profiles/own" => 'profiles#update_own',       as: :profiles_own
    post "profiles/own" => 'profiles#change_password',  as: :profiles_own
    get  "settings"     => 'settings#index',            as: :settings
    put  "settings"     => 'settings#update',           as: :settings
    scope ':season', :season => /\d{4}/ do
    end

    get   "farms"             => 'farms#index',        as: :farms_index
    get   "farms/:id"         => 'farms#show',         as: :farms_show
    get   "farms/:id/seasons" => 'farms#farm_seasons', as: :farm_seasons_show
    post  "farms"             => 'farms#create', as: :farms_create
    put   "farms/:id"         => 'farms#update', as: :farms_update

    post  "farm_in_seasons/active_deactive/:id" => 'farm_in_seasons#active_deactive', as: :active_deactive_farm_in_season

    get   "seasons"           => "seasons#index", as: :seasons_index
    get   "seasons/:id/farms" => "seasons#season_farms", as: :season_farms_show

    get    'fis/:fis_id/fields'     => 'fields#index',  as: :fields_index   # localhost:3000/api/fis/19/fields
    post   'fis/:fis_id/fields'     => 'fields#create', as: :fields_create  # localhost:3000/api/fis/19/fields
    put    'fis/:fis_id/fields/:id' => 'fields#update', as: :fields_update  # localhost:3000/api/fis/19/fields/10
    delete 'fis/:fis_id/fields/:id' => 'fields#delete', as: :fields_delete  # localhost:3000/api/fis/19/fields/10
    get 'dicts/get_precinct' => 'dicts#get_precinct', as: :get_precinct

    get 'dicts/search_plants'    => 'dicts#search_plants',    as: :search_plants
    get 'dicts/search_agri_pack' => 'dicts#search_agri_pack', as: :search_agri_pack
    get 'dicts/search_precinct'  => 'dicts#search_precinct',  as: :search_precinct
    get 'dicts/search_precinct_by_code' => 'dicts#search_precinct_by_code', as: :search_precinct_by_code

    post "files/upload_shape"  => 'files_upload#upload_shape', as: :upload_shape

    get 'parcels_by_geo'       => 'parcels#by_geo', as: :parcels
  end

  root :to => 'home#index'
  get  "help"          => 'home#help'
  get  "home/index"
  get  "home/wizard"
  post "home/wizard_completed"

end

app/models/accounts/change_password.rb
# encoding: utf-8

module Accounts
  class ChangePassword < Light::Model
    class MissingVariableError < StandardError; end

    attributes :old_password, :password, :password_confirmation
    attr_accessor :old_encrypted_password

    def encrypted_password
      @encrypted_password ||= generate_password(password)
    end

    validates :password, :presence => {message: 'hasło jest wymagane' }, :confirmation => {message: 'hasła nie zgadają się'}
    validate  :old_password_equality

    private

    def old_password_equality
      errors.add(:old_password, "hasło jest niepoprawne") unless old_passwords_equal?
    end

    def generate_password(password)
      EncryptorDecryptor.generate_password(password)
    end

    def old_passwords_equal?
      raise MissingVariableError.new('#old_encrypted_password missing') unless old_encrypted_password
      EncryptorDecryptor.passwords_equal?(old_encrypted_password, old_password)
    end

  end
end

app/models/accounts/email_confirmation.rb
# encoding: UTF-8
module Accounts
  class EmailConfirmation
    include ActiveModel::Model

    attr_accessor :confirmation_token

    validates_presence_of :confirmation_token, message: 'Brak tokena potwierdzającego'
    validate :user_for_token, :user_not_confirmed_yet

    def confirm
      user.tap do |u|
        u.extend(::Modules::User::Tokenable)
        u.auth_token = EncryptorDecryptor.generate_token
        u.extend_auth_token_in_days(Consts::AUTH_TOKEN_EXTEND_DAYS)
        u.confirmed_at = DateTime.now
        u.confirmation_token = nil

        u.save
      end
    end

    private

    def user_not_confirmed_yet
      if user && user.confirmed_at
        errors.add(:confirmation_token, 'Konto zostało już potwierdzone')
      end
    end

    def user_for_token
      unless user
        errors.add(:confirmation_token, 'Nie znaleziono konta oczekującego na potwierdzenie')
      end
    end

    def user
      @user ||= User.where("confirmation_token =?", confirmation_token).first
    end
  end
end

app/models/accounts/password_forgotten.rb
 module Accounts
  class PasswordForgotten
    include ActiveModel::Model

    attr_accessor :email

    validate :user_for_email, :user_status

    def reset_password
      user.reset_password_token = EncryptorDecryptor.generate_token
      user.reset_password_token_expire_at = Time.now + Consts::PASSWORD_RESET_TOKEN_DAYS
      user.save
      user
    end

    private

    def user
      @user ||= User.where("email =?", email.downcase).first
    end

    def user_for_email
      errors.add(:user, 'Brak konta dla podanego adresu email') unless user.present?
    end

    def user_status
      errors.add(:user, 'Konto zablokowane') if user.present? and user.locked_at.present?
    end
  end
end

app/models/accounts/registration.rb
# encoding: UTF-8

module Accounts
  class Registration
    include ActiveModel::Model

    attr_accessor :email, :password, :password_confirmation, :accept_terms

    validates_presence_of :email, message: 'Podaj email'
    validates_presence_of :password, message: 'Podaj hasło'
    validates_presence_of :password_confirmation, message: 'Powtórz hasło'

    validates_format_of :email, :with => Consts::EMAIL_REGEX, message: 'Email ma nieprawidłowy format'
    validate :email_not_taken, :passwords_are_equal, :terms_accepted

    def register
      new_user.save
      new_user
    end

    private

    def email_not_taken
      user = User.where("email =?", email.downcase).first

      if user.present?
        errors.add(:email, 'Konto o podanym adresie email już istnieje.')
      end
    end

    def passwords_are_equal
      errors.add(:password, 'Hasło i jego powtórzenie muszą być identyczne') unless password == password_confirmation
    end

    def terms_accepted
      errors.add(:accept_terms, 'Musisz zaakceptować regulamin') unless accept_terms.try(:downcase) == 'on'
    end

    def new_user
      @new_user ||= User.new.tap do|user|
        user.email = email.downcase
        user.encrypted_password = EncryptorDecryptor.generate_password(password)
        user.confirmation_token = EncryptorDecryptor.generate_token
      end
    end
  end
end

app/models/accounts/reset_password_finish.rb
# encoding: utf-8

module Accounts
  class ResetPasswordFinish
    include ActiveModel::Model

    attr_accessor :reset_password_token, :password, :password_confirmation

    validates_presence_of :password, message: 'Podaj hasło'
    validates_presence_of :password_confirmation, message: 'Powtórz hasło'
    validate :user_for_token, :user_status

    def initialize(reset_password_token, opts={})
      super(opts)

      @reset_password_token = reset_password_token
    end

    def reset!
      user.encrypted_password = EncryptorDecryptor::generate_password(password)
      user.reset_password_token = nil
      user.reset_password_token_expire_at = nil
      user.failed_attempts = 0
      user.save
      user
    end

    private

    def user
      @user ||= User.where("reset_password_token =?", reset_password_token).first
    end

    def user_for_token
      errors.add(:user, 'Konto nie zostało znalezione') unless user.present?
    end

    def user_status
      return unless user.present?

      if user.reset_password_token_expire_at.present? and user.reset_password_token_expire_at < Time.now
        errors.add(:user, 'Upłynął czas na zresetowanie hasła')
      end

      errors.add(:user, 'Konto zablokowane') if user.locked_at.present?
    end

    def password_policy
      unless password == password_confirmation
        errors.add(:password, 'Hasło i jego powtórzenie muszą być takie same')
      end
    end
  end
end

app/models/accounts/reset_password_start.rb
# encoding: utf-8

module Accounts
  class ResetPasswordStart
    include ActiveModel::Model

    attr_accessor :reset_password_token

    validate :user_for_token, :user_status

    def initialize(reset_password_token)
      @reset_password_token = reset_password_token
    end

    def user
      @user ||= User.where("reset_password_token =?", reset_password_token).first
    end

    private

    def user_for_token
      errors.add(:user, 'Konto nie zostało znalezione') unless user.present?
    end

    def user_status
      return unless user.present?

      if user.reset_password_token_expire_at.present? and user.reset_password_token_expire_at < Time.now
        errors.add(:user, 'Upłynął czas na zresetowanie hasła')
      end

      errors.add(:user, 'Konto zablokowane') if user.locked_at.present?
    end
  end
end

app/controllers/accounts_controller.rb
# encoding: utf-8

class AccountsController < ApplicationController
  layout 'empty'

  before_filter :authorize, only: [:login]

  #TODO: We should move this to the translation yaml files
  MESSAGES = {
    account_created: 'Konto utworzone. Odbierz email z linkiem potwierdzającym rejestrację',
    account_creation_fail: 'Konto nie zostało utworzone',
    account_reset_password_email_sent: 'Odbierz email aby zmienić swoje hasło',
    account_reset_password_email_send_fail: 'Hasło nie może zostać zresetowane.',
    account_password_changed: 'Hasło zmienione'
  }

  def index
  end

  def login
    session[:token] = @current_user.auth_token
    redirect_to :controller => 'home', :action => 'wizard'
  end

  def logout
    authorize_by_token

    @current_user.auth_token = nil
    @current_user.auth_token_expire_at = nil
    @current_user.save
    session[:token] = nil
  rescue Authenticate::AuthFailError
  end

  def register
    registration = Accounts::Registration.new(params[:registration])

    if registration.valid?
      user = registration.register
      UserMailer.registration_confirmation(user.email, url: confirm_email_url(user.confirmation_token), help_url: help_url)

      render_success_json(messages_for_status(:account_created), nil)
    else
      json = {
        status: Consts::Response::ERROR,
        message: messages_for_status(:account_creation_fail),
        errors: registration.errors.first[1],
        data: params
      }

      render json: json
    end
  end

  def confirm_email
    confirmation = Accounts::EmailConfirmation.new(confirmation_token: params[:confirmation_token])

    if confirmation.valid?
      @current_user = confirmation.confirm
      session[:token] = @current_user.auth_token
      redirect_to :controller => 'home', :action => 'wizard'
    else
      flash[:alert] = confirmation.errors.first[1]
      redirect_to :login_and_register_page
    end
  end

  def forgot_password
    password_forgotten = Accounts::PasswordForgotten.new(params[:forgotPassword])

    if password_forgotten.valid?
      user = password_forgotten.reset_password

      opts = {
        url: reset_password_start_url(user.reset_password_token),
        help_url: help_url
      }
      UserMailer.reset_password_confirmation(user.email, opts)
      render_success_json(messages_for_status(:account_reset_password_email_sent), nil)
    else
      json = {
        status: Consts::Response::ERROR,
        message: messages_for_status(:account_reset_password_email_send_fail),
        errors: password_forgotten.errors.first[1],
        data: params
      }

      render json: json
    end
  end

  def reset_password_start
    reset_password = Accounts::ResetPasswordStart.new(params[:reset_password_token])

    if reset_password.valid?
      proffer current_user: reset_password.user
    else
      flash[:alert] = reset_password.errors.first[1]
      redirect_to :login_and_register_page
    end
  end

  def reset_password_finish
    reset_password = Accounts::ResetPasswordFinish.new(params[:reset_password_token], params[:resetPassword])

    if reset_password.valid?
      reset_password.reset!
      flash[:notice] = messages_for_status(:account_password_changed)
      redirect_to :login_and_register_page
    else
      flash[:alert] = reset_password.errors.first[1]
      redirect_to reset_password_start_url(reset_password.user.try(:reset_password_token))
    end
  end

  private

  def messages_for_status(stat)
    MESSAGES[stat]
  end
end

app/views/accounts/_forgot_password.html.haml
#forgot-box.forgot-box.widget-box.no-border.mt-50
  .toolbar.clearfix.bg-green.center
    %h1.mt-10
      = image_tag('efarm_logo.png', class: 'logo-img')
      %span.white efarm portal
  .widget-body
    .widget-main
      %h4.header.red.lighter.bigger
        %i.icon-key
        Odzyskiwanie hasła
      .space-6
      %p
        Podaj swój adres email. Otrzymasz maila z linkiem do strony umożliwiającej zmianę hasła.
        %form#forgotForm{action: "#{forgot_password_url}", method: 'POST'}
          %fieldset
            .control-group
              %label.block.clearfix.js-control-group
                %span.block.input-icon.input-icon-right
                  %input.form-control{name: "forgotPassword[email]", placeholder: "Email", type: "email"}/
                  %i.icon-envelope
            .clearfix
              %button#forgotSubmitBtn.btn.btn-primary.btn-block.bolder
                %i.icon-check
                Wyślij

  .toolbar.align-right.bg-green
    %a.back-to-login-link{href: "#"}
      Powrót do logowania
      %i.icon-arrow-right

app/views/accounts/_register.html.haml
#signup-box.login-box.widget-box.no-border.mt-50
  .toolbar.clearfix.bg-green.center
    %h1.mt-10
      = image_tag('efarm_logo.png', class: 'logo-img')
      %span.white efarm portal
  .widget-body
    .widget-main
      %h4.header.blue.bigger
        %i.icon-user.blue
        Tworzenie konta
      .space-6
      %p Wprowadź swoje dane aby rozpocząć:
      %form#singupForm{action: 'register', method: 'POST'}
        %fieldset
          %label.block.clearfix.js-control-group
            %span.block.input-icon.input-icon-right
              %input.form-control{name: "registration[email]", placeholder: "Email", type: "email"}
              %i.icon-envelope
          %label.block.clearfix.js-control-group
            %span.block.input-icon.input-icon-right
              %input.form-control#registrationPassword{name: "registration[password]", placeholder: "Hasło", type: "password"}
              %i.icon-lock
          %label.block.clearfix.js-control-group
            %span.block.input-icon.input-icon-right
              %input.form-control{name: "registration[password_confirmation]", placeholder: "Powtórz hasło", type: "password"}
              %i.icon-retweet
          %label.block.clearfix.js-control-group
            %input.ace{ name: "registration[accept_terms]", type: "checkbox", checked: "true" }
            %span.lbl
              Akceptuję
              %a{href: "#"} Regulamin Użytkowania

          .space-12
          .clearfix
            %button.width-40.pull-left.btn.btn-small{type: "reset"}
              %i.icon-refresh
              Wyczyść
            %button#singupSubmitBtn.width-50.pull-right.btn.btn-small.btn-primary
              %i.icon-check
              Rejestruj
  .toolbar.clearfix.bg-green
    %div
      %a.back-to-login-link.login-footer-link.bolder{href: "#"}
        %i.icon-arrow-left
        Powrót do logowania

app/views/accounts/index.html.haml
.col-sm-10.col-sm-offset-1
  .login-container
    .position-relative
      #login-box.login-box.visible.widget-box.no-border.mt-50
        .toolbar.clearfix.bg-green.center
          %h1.mt-10
            = image_tag('efarm_logo.png', class: 'logo-img')
            %span.white efarm portal
          / %h4.white synopsisproject.pl
        .widget-body
          .widget-main
            %h4.header.blue.lighter.bigger
              %i.icon-coffee.blue
              Proszę wprowadzić swoje dane
            .space-6
            %form#loginForm{action: "#{login_url}", method: 'POST'}
              %input{hidden: "returnUrl", value: '#'}
              %fieldset
                %label.block.clearfix.js-control-group
                  %span.block.input-icon.input-icon-right
                    %input.form-control{name: "email", placeholder: "Email", type: "text", value: "", autofocus: "true"}
                    %i.icon-envelope
                %label.block.clearfix.js-control-group
                  %span.block.input-icon.input-icon-right
                    %input.form-control{name: "password", placeholder: "Hasło", type: "password"}
                    %i.icon-lock

                .clearfix
                  %button#loginSubmitBtn.btn.btn-primary.btn-block.bolder
                    %i.icon-key
                    Zaloguj
                .space-4
            .social-or-login.center
              %span.bigger-110 Lub zaloguj się przez
            .social-login.center
              %a.btn.btn-primary
                %i.icon-facebook
              %a.btn.btn-info
                %i.icon-twitter
              %a.btn.btn-danger
                %i.icon-google-plus

        .toolbar.clearfix.bg-green.center
          %div
            %a.forgot-password-link.login-footer-link.bolder{href: "#"}
              %i.icon-arrow-left
              Nie pamiętam hasła


        %a.btn.btn-block.btn-primary.bolder.new-user-button.user-signup-link{ href: "#" }
          Nie mam konta, chcę założyć nowe
          %i.icon-arrow-right
      = render "accounts/forgot_password"
      = render "accounts/register"


- content_for :scripts do
  = javascript_include_tag 'page_account'
  - if flash[:alert]
    :coffeescript

      window.App.Message =
        kind: "error"
        text: "#{flash[:alert]}"

  - if flash[:notice]
    :coffeescript

      window.App.Message =
        kind: "info"
        text: "#{flash[:notice]}"

  :coffeescript

    window.App.Urls.Accounts =
      forgottenPassword: "/accounts/forgotten"
      register: "#{register_url}"

    accountController = new window.App.Controllers.Account();

app/views/accounts/logout.html.haml
.main-container
  .login-screen
  .main-content
    .center
      %h1.white Do zobaczenia

app/views/accounts/reset_password_start.html.haml
.col-sm-10.col-sm-offset-1
  .login-container
    .position-relative
      #login-box.login-box.visible.widget-box.no-border.mt-50
        .toolbar.clearfix.bg-green.center
          %h1.mt-10
            = image_tag('efarm_logo.png', class: 'logo-img')
            %span.white efarm portal
        .widget-body
          .widget-main
            %h4.header.blue.bigger
              %i.icon-lock.blue
              Formularz zmiany hasła
              .space-6
              %form#resetPasswordForm{action: "#{reset_password_finish_url(current_user.reset_password_token)}", method: 'POST'}
                %fieldset
                %label.block.clearfix.js-control-group
                  %span.block.input-icon.input-icon-right
                    %input#password.form-control{name: "resetPassword[password]", placeholder: "Nowe hasło", type: "password", value: ""}
                      %i.icon-lock
                  %label.block.clearfix.js-control-group
                    %span.block.input-icon.input-icon-right
                      %input.form-control{name: "resetPassword[password_confirmation]", placeholder: "Powtórz hasło", type: "password", value: ""}
                      %i.icon-retweet
                  .clearfix
                    %button#resetPasswordSubmitBtn.btn.btn-danger.btn-block.bolder
                      %i.icon-refresh
                      Zresetuj
- content_for :scripts do
  = javascript_include_tag 'page_account'
  - if @message
    :coffeescript
      window.App.Message =
        kind: "#{@message.status}"
        text: "#{@message.text}"

  :coffeescript
    accountController = new window.App.Controllers.Account();